MODIFICADOR = 150
LARGURA_TELA = 800
ALTURA_TELA = 600
FPS = 60
TITULO_JOGO = "Defend the Castle"

BRANCO = (255, 255, 255)
PRETO = (0, 0, 0)
CINZA = (212, 212, 212)
MARROM = (110, 70, 40)
CEU = (40, 45, 70)
PEDRA = (90, 90, 100)
VERMELHO = (200, 50, 50)
AMARELO = (240, 200, 60)
VERDE = (60, 180, 75)

JOGADOR_MODIFICADOR = MODIFICADOR
JOGADOR_VELOCIDADE = LARGURA_TELA / JOGADOR_MODIFICADOR
JOGADOR_VIDAS = 3
INTERVALO_DISPARO = 400

# Onde o arqueiro nasce: "esquerda", "centro" ou "direita"
ARQUEIRO_POSICAO_INICIAL = "centro"

FLECHA_VELOCIDADE = 7

INIMIGOS_BASE = 2

ESQUELETO_MODIFICADOR = MODIFICADOR * 2.5
ESQUELETO_VELOCIDADE = ALTURA_TELA / ESQUELETO_MODIFICADOR
ESQUELETO_VIDA = 1
ESQUELETO_PONTOS = 10

MORCEGO_MODIFICADOR = MODIFICADOR * 2
MORCEGO_VELOCIDADE = ALTURA_TELA / MORCEGO_MODIFICADOR
MORCEGO_VIDA = 1
MORCEGO_PONTOS = 10

ORC_MODIFICADOR = MODIFICADOR * 3.5
ORC_VELOCIDADE = ALTURA_TELA / ORC_MODIFICADOR
ORC_VIDA = 2
ORC_PONTOS = 20

# Em que ordem os inimigos aparecem nas ondas. Quando a lista acaba, ela recomeca do inicio
ORDEM_DOS_INIMIGOS = ["esqueleto", "morcego", "orc"]

ONDA_MAXIMA = 10
LINHA_CASTELO = ALTURA_TELA - 70

MAX_RANKING = 5
TAMANHO_MAX_NOME = 10

CAMINHO_RECORDE = "data/recorde.txt"
CAMINHO_RANKING = "data/ranking.txt"

IMAGEM_ARQUEIRO = "assets/imagens/arqueiro.png"
IMAGEM_ESQUELETO = "assets/imagens/esqueleto.png"
IMAGEM_MORCEGO = "assets/imagens/morcego.png"
IMAGEM_ORC = "assets/imagens/orc.png"
IMAGEM_FLECHA = "assets/imagens/flecha.png"

ESCALA_ARQUEIRO = 0.5
ESCALA_ESQUELETO = 2.0
ESCALA_MORCEGO = 0.4
ESCALA_ORC = 2.0
ESCALA_FLECHA = 1.0
